// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWqiAaXHneUxaU9Gvi_EXMkJuhj0XCtk',
    appId: '1:983642926632:web:bab14b2935360ad06d8f1d',
    messagingSenderId: '983642926632',
    projectId: 'easy-a2a74',
    authDomain: 'easy-a2a74.firebaseapp.com',
    storageBucket: 'easy-a2a74.appspot.com',
    measurementId: 'G-Q2Y6YDS7Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOGeeNALcv16a-x4hpHpxhC7EBp1_fdQo',
    appId: '1:983642926632:android:6502dc343ab9150f6d8f1d',
    messagingSenderId: '983642926632',
    projectId: 'easy-a2a74',
    storageBucket: 'easy-a2a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhJBJzsI0fcFAUyacBZESr7wDDP4Embc',
    appId: '1:983642926632:ios:857538d21e3356186d8f1d',
    messagingSenderId: '983642926632',
    projectId: 'easy-a2a74',
    storageBucket: 'easy-a2a74.appspot.com',
    iosBundleId: 'com.example.easyred',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhJBJzsI0fcFAUyacBZESr7wDDP4Embc',
    appId: '1:983642926632:ios:857538d21e3356186d8f1d',
    messagingSenderId: '983642926632',
    projectId: 'easy-a2a74',
    storageBucket: 'easy-a2a74.appspot.com',
    iosBundleId: 'com.example.easyred',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWqiAaXHneUxaU9Gvi_EXMkJuhj0XCtk',
    appId: '1:983642926632:web:c496bb3051682ebf6d8f1d',
    messagingSenderId: '983642926632',
    projectId: 'easy-a2a74',
    authDomain: 'easy-a2a74.firebaseapp.com',
    storageBucket: 'easy-a2a74.appspot.com',
    measurementId: 'G-P5JKN8RWFE',
  );
}
